### ISSUE TITLE
GPIOZERO version 2.0 problem

### ISSUE THREAD

**Issue by gldrplt** [gpiozero/gpiozero#1103]
When I try to define an LED using version 2.0, I get an error message.  However the same code works fine using version 1.6.2

The code is:

from gpiozero import LED
a = LED(4, True, True)

here is the error message
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gpiozero import LED
>>> a = LED(4, True, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DigitalOutputDevice.__init__() takes from 1 to 2 positional arguments but 4 were given
>>> 

Any ideas what is wroing?

**Comment by bennuttall** [comment]
It's because you're passing `True, True` as positional arguments, but they are keyword-only arguments. You need to specify the arguments not just their values in order:

```python
a = LED(4, active_high=True, initial_value=True)
```

It was never documented that you could pass them positionally, and in 1.x this was uninforcable due to Python 2 compatibility which we've dropped in 2.x.

It's described in the documentation: https://gpiozero.readthedocs.io/en/latest/compat.html#keyword-arguments
