### ISSUE TITLE
ButtonBoard release events?

### ISSUE THREAD

**Issue by bennuttall** [gpiozero/gpiozero#761]
GPIO Zero v1.5.0, mock factory.

Looks like release events fire as press events:

```python
In [1]: from gpiozero import *
In [2]: bb = ButtonBoard(2, 3)
In [3]: pins = bb[0].pin, bb[1].pin
In [4]: bb.when_pressed = lambda: print("bb pressed", tuple(bb.value))
In [5]: bb.when_released = lambda: print("bb released", tuple(bb.value))
In [6]: pins[0].drive_low()
bb pressed (1, 0)
In [7]: pins[0].drive_high()
bb pressed (0, 0)
```

**Comment by lurch** [comment]
Hmmm, well spotted Mr Nuttall! :bug: 

I tried digging into it a bit, and I _think_ this is because `ButtonBoard._fire_events()` calls `super(ButtonBoard, self)._fire_events(ticks, new_value)`, which I believe then bubbles up to `EventsMixin`, and `EventsMixin._fire_events` expects a `.is_active` and not a `.value`.

And so because `ButtonBoard.value` is a tuple, which always evaluates to True, `EventsMixin` always thinks the ButtonBoard is being "activated" i.e. pressed. https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/boards.py#L298

```python
>>> bool((0,0))
True
```

This is all @waveform80 magic, so probably something that he'll need to fix :wink:
